name: Build and push imagen Dotnet

on:
  workflow_dispatch:

jobs:
  extract_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from changelog
        id: get_version
        shell: bash
        run: |
          version=$(grep -oPm1 '(?<=## \[)[^]]+' CHANGELOG.md)

          if [ -z "$version" ]; then
            echo "No se pudo obtener la versión desde CHANGELOG.md"
            exit 1
          fi

          echo "Extracted version: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

  build:
    name: Build Docker image BiobibliotecaAPI
    needs: extract_version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate build Dockerfile
        run: |
          docker build \
            -t "biblioteca-api:${{ needs.extract_version.outputs.version }}" \
            .